"""
Django settings for level_repository project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

load_dotenv()


def env_flag(name: str, default: bool = False) -> bool:
    """Parse common truthy/falsey env var values safely."""
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "t", "yes", "y", "on"}


def sanitize_postgres_url(url: str) -> str:
    """Drop unsupported postgres query params that can break psycopg2 DSN parsing."""
    parts = urlsplit(url)
    if parts.scheme not in {"postgres", "postgresql"}:
        return url

    allowed_query_keys = {
        "sslmode",
        "application_name",
        "connect_timeout",
        "options",
        "target_session_attrs",
        "gssencmode",
        "keepalives",
        "keepalives_idle",
        "keepalives_interval",
        "keepalives_count",
        "channel_binding",
    }
    blocked_prefixes = ("supa",)

    filtered_query = [
        (k, v)
        for k, v in parse_qsl(parts.query, keep_blank_values=True)
        if k in allowed_query_keys and not k.lower().startswith(blocked_prefixes)
    ]
    return urlunsplit((parts.scheme, parts.netloc, parts.path, urlencode(filtered_query), parts.fragment))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = ["appel.pythonanywhere.com", "localhost", "127.0.0.1", ".vercel.app", ".now.sh", "workshop.appelgame.net"]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'levels',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'level_repository.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'level_repository.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# Use PostgreSQL in production (Vercel) or when explicitly enabled.
if env_flag("VERCEL") or env_flag("USE_POSTGRES"):
    # Prefer explicit Postgres var first, then generic DATABASE_URL.
    database_url_candidates = [
        os.getenv("POSTGRES_URL"),
        os.getenv("DATABASE_URL"),
    ]
    database_urls = [url for url in database_url_candidates if url]

    if not database_urls:
        raise ValueError("DATABASE_URL/POSTGRES_URL is not set for production.")

    last_error = None
    for raw_url in database_urls:
        try:
            database_url = sanitize_postgres_url(raw_url)
            DATABASES = {
                "default": dj_database_url.parse(
                    database_url,
                    conn_max_age=600,
                    conn_health_checks=True,
                    ssl_require=True,
                )
            }
            break
        except Exception as exc:
            last_error = exc
    else:
        raise ValueError(
            "Could not parse a valid PostgreSQL connection string from POSTGRES_URL or DATABASE_URL. "
            "Check Vercel environment variables."
        ) from last_error
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# WhiteNoise configuration for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

LOGIN_REDIRECT_URL = '/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    'https://turbowarp.org',
    'https://workshop.appelgame.net',
]

# Allow common localhost development origins (include ports explicitly)
CORS_ALLOWED_ORIGINS += [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]
