# Generated by Django 4.0.6 on 2024-10-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='difficulty',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
