# Generated by Django 4.0.6 on 2024-10-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_alter_level_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='rated_difficulty',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='difficulty',
            field=models.CharField(default='0e', max_length=5),
        ),
    ]
