# Generated by Django 4.0.6 on 2024-10-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_level_rated_difficulty_alter_level_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='level',
            name='rated_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
