# Generated by Django 4.0.6 on 2024-10-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0004_alter_level_difficulty_alter_level_rated_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
