# Generated by Django 4.0.6 on 2024-10-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0005_level_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_code',
            field=models.TextField(max_length=10000),
        ),
    ]
