# Generated by Django 4.0.6 on 2024-10-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0006_alter_level_description_alter_level_level_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_ratings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
