# Generated by Django 4.0.6 on 2024-10-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0009_alter_profile_stats_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='mod_category',
            field=models.CharField(choices=[('appel', 'Appel'), ('appelp', 'Appel+'), ('appelm', 'Appel Multiplayer'), ('sheepel', 'Sheepel')], default='appel', max_length=50),
        ),
    ]
