# Generated by Django 4.0.6 on 2025-03-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0010_level_mod_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='original_uploader',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
