# Generated by Django 4.0.6 on 2025-03-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0011_level_original_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='original_uploader',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
