# Generated by Django 6.0 on 2025-12-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0012_alter_level_original_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='difficulty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='level',
            name='mod_category',
            field=models.CharField(choices=[('appel', 'Appel'), ('appelp', 'Appel+'), ('appelm', 'Appel Multiplayer'), ('sheepel', 'Sheepel'), ('appel-playground', 'Appel Playground')], default='appel', max_length=50),
        ),
        migrations.AlterField(
            model_name='level',
            name='rated_difficulty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stats',
            field=models.JSONField(default={'levelpoints': 0, 'levels_completed': []}),
        ),
    ]
