# Generated by Django 6.0 on 2025-12-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0013_alter_level_difficulty_alter_level_mod_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='difficulty',
            field=models.FloatField(default=0, help_text='Difficulty in the Punter Scale'),
        ),
    ]
