# Generated by Django 6.0 on 2025-12-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0014_alter_level_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='difficulty',
            field=models.FloatField(default=0, help_text='The difficulty (in the Punter scale, more info here https://appel.miraheze.org/wiki/Difficulty)'),
        ),
    ]
