# Generated by Django 6.0 on 2026-01-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0017_profile_difficulty_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='difficulty',
            field=models.FloatField(default=0, help_text="The difficulty (in the Punter scale, more info <a href='https://appel.miraheze.org/wiki/Difficulty'>here</a>)"),
        ),
        migrations.AlterField(
            model_name='level',
            name='original_uploader',
            field=models.CharField(blank=True, default='', help_text='The original creator of the level. Leave blank if this was you.', max_length=100, null=True),
        ),
    ]
