# Generated by Django 6.0 on 2026-01-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0018_alter_level_difficulty_alter_level_original_uploader'),
        ('levels', '0018_profile_dark_mode'),
    ]

    operations = [
    ]
