# Generated by Django 6.0.4 on 2026-04-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0019_merge_20260123_1020'),
        ('levels', '0020_alter_profile_difficulty_system_choices'),
    ]

    operations = [
    ]
