# Generated by Django 6.0.4 on 2026-04-24 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0021_merge_20260424_1634'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='difficulty_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='quality_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LevelRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_rating', models.PositiveSmallIntegerField()),
                ('quality_rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='levels.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('level', 'user'), name='unique_level_rating_per_user')],
            },
        ),
    ]
