# Generated by Django 6.0.4 on 2026-04-24 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0022_level_difficulty_rating_level_quality_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelrating',
            name='difficulty_rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='levelrating',
            name='quality_rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
