# Generated by Django 6.0.4 on 2026-04-24 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0023_alter_levelrating_difficulty_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='rated_difficulty',
        ),
        migrations.AlterField(
            model_name='levelrating',
            name='quality_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
