# Generated by Django 6.0.4 on 2026-04-24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0026_profile_bio_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelrating',
            name='difficulty_rating',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(15),
                ],
            ),
        ),
    ]
