# Generated by Django 6.0.4 on 2026-04-24

from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations


def backfill_creator_level_ratings(apps, schema_editor):
    Level = apps.get_model('levels', 'Level')
    LevelRating = apps.get_model('levels', 'LevelRating')

    existing_pairs = set(LevelRating.objects.values_list('level_id', 'user_id'))
    ratings_to_create = []

    for level in Level.objects.only('id', 'creator_id', 'difficulty').iterator():
        if not level.creator_id:
            continue

        pair = (level.id, level.creator_id)
        if pair in existing_pairs:
            continue

        try:
            difficulty = Decimal(str(level.difficulty if level.difficulty is not None else 0))
        except Exception:
            difficulty = Decimal('0')

        difficulty = max(Decimal('0'), min(Decimal('15'), difficulty))
        difficulty = difficulty.quantize(Decimal('0.01'), rounding=ROUND_HALF_UP)

        ratings_to_create.append(
            LevelRating(
                level_id=level.id,
                user_id=level.creator_id,
                difficulty_rating=difficulty,
                quality_rating=None,
            )
        )

    if ratings_to_create:
        LevelRating.objects.bulk_create(ratings_to_create, batch_size=500)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0027_alter_levelrating_difficulty_rating'),
    ]

    operations = [
        migrations.RunPython(backfill_creator_level_ratings, noop_reverse),
    ]
