# Generated by Django 6.0.4 on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0028_backfill_creator_level_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scratch_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
