# Generated by Django 6.0.4 on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0029_profile_scratch_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='other_creators',
            field=models.TextField(blank=True, default='', help_text='Optional: comma-separated usernames or names.'),
        ),
        migrations.AddField(
            model_name='level',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='level',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Optional YouTube link.'),
        ),
    ]
