# Generated by Django 6.0.4 on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0030_level_other_creators_url_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_code',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='level',
            name='mod_category',
            field=models.CharField(
                choices=[
                    ('appel', 'Appel'),
                    ('appelp', 'Appel+'),
                    ('appelm', 'Appel Multiplayer'),
                    ('sheepel', 'Sheepel'),
                    ('appel-playground', 'Appel Playground'),
                    ('custom', 'Custom'),
                ],
                default='appel',
                max_length=50,
            ),
        ),
    ]
