# Generated by Django 6.0 on 2026-04-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0033_alter_level_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord_user_id',
            field=models.CharField(blank=True, default='', help_text='Your Discord user ID for completion pings.', max_length=100),
        ),
    ]
