# Generated by Django 6.0 on 2026-04-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0034_profile_discord_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Your country for your profile flag.', max_length=2),
        ),
    ]
