# Generated by Django 6.0 on 2026-04-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0035_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Use dark mode theme.'),
        ),
    ]
