# Generated by Django 6.0 on 2026-04-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0036_profile_dark_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dark_mode',
        ),
    ]
