# Generated by Django 6.0 on 2026-07-01 19:22

from django.db import migrations, models


def set_empty_tags_for_existing_levels(apps, schema_editor):
    Level = apps.get_model('levels', 'Level')
    Level.objects.filter(tags__isnull=True).update(tags=[])
    Level.objects.exclude(tags__isnull=False).update(tags=[])


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0038_cookieconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Choose up to 10 tags for this level.'),
        ),
        migrations.RunPython(set_empty_tags_for_existing_levels, migrations.RunPython.noop),
    ]
